### ISSUE TITLE
`iter-yield` inside `dolist` crashes `iter2--convert-function-body` when defining function

### ISSUE THREAD

**Issue by rhaps0dy** [doublep/iter2#2]
To reproduce, on `master`, eval:
```elisp
(iter2-defun f ()
  (dolist (e '(1 2 3))
    (iter-yield e)))
```
which gives error `wrong-type-argument listp $value`. Fair enough.

Mysteriously, however, `macroexpand`ing the above is fine:
```elisp
(macroexpand '(iter2-defun f ()
  (dolist (e '(1 2 3))
    (iter-yield e))))
```
gives no error.

I don't know how to start fixing this, since `macroexpand` works just fine.

**Comment by doublep** [comment]
Works for me:

    ~/iter2$ eldev eval "(iter2-defun f () (dolist (e '(1 2 3)) (iter-yield e)))" "(iter-do (k (f)) (print k))"
    f
    
    1
    
    2
    
    3
    nil

Also works inside Emacs. Which Emacs version do you use?

**Comment by rhaps0dy** [comment]
I use Emacs 29.0.50, which is the `master` from a few weeks ago. It works for me too now. I must have `eval`ed something that made this go wrong in my old Emacs session, and I did not restart it and try again when submitting the issue.

I'm very sorry about wasting your time, I'll do better next time.

**Comment by doublep** [comment]
>  I must have evaled something that made this go wrong in my old Emacs session

That's why I prefer to use `eldev` (or `emacs --batch`) for reproducing bugs: you always get a fresh and standardized evaluation environment.
